#!/bin/sh
### BEGIN INIT INFO
# Provides:          stream-m
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop strea-m server
### END INIT INFO

case $1 in
    start)
        echo "Starting stream-m ..."
        if [ ! -f /var/run/stream-m.pid ]; then
            cd /opt/stream-m/dist && nohup java -jar /opt/stream-m/dist/stream-m.jar /opt/stream-m/dist/server.properties.sample 2>> /dev/null >> /dev/null &
            echo $! > /var/run/stream-m.pid
            echo "stream-m started ..."
        else
            echo "stream-m is already running ..."
        fi
    ;;
    stop)
        if [ -f /var/run/stream-m.pid ]; then
            PID=$(cat /var/run/stream-m.pid);
            echo "Stopping stream-m ..."
            kill $PID;
            echo "stream-m stopped ..."
            rm /var/run/stream-m.pid
        else
            echo "stream-m is not running ..."
        fi
    ;;
    status)
        if [ -f /var/run/stream-m.pid ]; then
            PID=$(cat /var/run/stream-m.pid);
            kill -0 $PID
            if [ "$?" -ne 0 ]; then
                echo "stream-m is not running..."
                exit 1
            fi
            exit 0
        else
            echo "stream-m is not running ..."
            exit 1
        fi
    ;;
    restart)
        service stream-m stop

        sleep 2

        service stream-m start
    ;;
esac
